channels:
- conda-forge
dependencies:
- python=3.8.10
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - psutil==5.8.0
  - scikit-learn==0.23.2
  - scikit-learn==1.0.1
  - typing-extensions==3.10.0.2
  - uuid==1.30
name: mlflow-env
